language: python

python:
  - "2.7"

services:
  - mysql

install:
  - sudo service mysql stop
  - sudo apt-get install python-software-properties
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
  - sudo add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu precise main'
  - sudo apt-get update
  - sudo apt-get purge -y mysql-common
  - sudo apt-get install mariadb-server mariadb-common libmariadbclient-dev
  
  - CFLAGS=-O0 pip install -r requirements.txt
  - pip install --editable .

script: 
    cd ./test_sites/ &&
    frappe --reinstall test_site &&
    frappe -b test_site &&
    frappe --run_tests test_site

before_script:
  - mysql -e 'create database travis' &&
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root

