language: python
dist: trusty

matrix:
  include:
  - python: "2.7"
    env: PYTHON=python2
  - python: "3.3"
    env: PYTHON=python3
  - python: "3.4"
    env: PYTHON=python3
  - python: "3.5"
    env: PYTHON=python3
  - python: "3.6"
    env: PYTHON=python3
  - python: "3.7-dev"
    env: PYTHON=python3
  - python: "pypy3"
    env: PYTHON=pypy3
  allow_failures:
    - env: PYTHON=python3 PYTHON=pypy3

services:
  - mysql

before_script:
  - mysql -u root -ptravis -e 'CREATE DATABASE test_frappe'
  - echo "USE mysql;\nCREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe';\nFLUSH PRIVILEGES;\n" | mysql -u root -ptravis
  - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost';\n" | mysql -u root -ptravis

  - cd ~/frappe-bench
  - bench use test_site
  - bench reinstall --yes
  - bench setup-help
  - bench scheduler disable
  - bench start &
  - sleep 20

install:
  - sudo rm /etc/apt/sources.list.d/mongodb*.list
  - sudo rm /etc/apt/sources.list.d/docker.list
  - sudo apt-get purge -y mysql-common mysql-server mysql-client
  - nvm install v8.10.0
  
  - wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py

  - sudo python install.py --develop --user travis --without-bench-setup
  - sudo pip install -e ~/bench

  - rm $TRAVIS_BUILD_DIR/.git/shallow
  - cd ~/ && bench init frappe-bench --python $PYTHON --frappe-path $TRAVIS_BUILD_DIR
  - cp -r $TRAVIS_BUILD_DIR/test_sites/test_site ~/frappe-bench/sites/

script:
  - bench run-tests
