language: python

python:
  - "2.7"

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install --editable .

script: 
    cd ./test_sites/ &&
    webnotes --reinstall -v test_site &&
    webnotes --run_tests -v test_site

branches:
  only:
    - testing

before_script:
  - mysql -e 'create database travis' &&
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root

