language: python

python:
  - "2.7"

services:
  - mysql

install:
  - CFLAGS=-O0 pip install -r requirements.txt --upgrade
  - pip install --editable .

script: 
    cd ./test_sites/ &&
    frappe --reinstall -v test_site &&
    frappe -b -v test_site &&
    frappe --run_tests -v test_site

before_script:
  - mysql -e 'create database travis' &&
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root

