version: 0.2

env:
  variables:
    FRAPPE_USER: "frappe"
    BENCH_DIR: "/home/frappe/frappe-bench"

phases:
  install:
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws configure set aws_access_key_id $ACCESS_KEY
      - aws configure set aws_secret_access_key $SECRET_KEY
      - aws configure set region ap-south-1
      
  build:
    commands:
      - echo Build started on `date`
      - aws ssm send-command --document-name "AWS-RunAnsiblePlaybook" --targets '[{"Key":"tag:bloomstack","Values":["true"]}]' --parameters '{"playbook":["- hosts: 127.0.0.1\n tasks:\n - name: BENCH UPDATE KARLO\n command: bench update\n args:\n chdir: ~/frappe-bench"],"playbookurl":[""],"extravars":["SSM=True"],"check":["False"]}' --timeout-seconds 30 --max-concurrency "100" --max-errors "1" --region ap-south-1
