version: 0.2

env:
  variables:
    FRAPPE_USER: "frappe"
    BENCH_DIR: "/home/frappe/frappe-bench"

phases:
  install:
    commands:
      - apt-get install sshpass
      
  build:
    commands:
      - echo Build started on `date`
      - sshpass -p $SSH_PASS ssh $SSH_USER@$SERVER "cd $BENCH_DIR && bench update"
      - echo Please Work!
