version: 0.2

phases:
  install:
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws configure set aws_access_key_id $ACCESS_KEY
      - aws configure set aws_secret_access_key $SECRET_KEY
      - aws configure set region ap-south-1
      
  build:
    commands:
      - echo Build started on `date`
      - aws ssm send-command --document-name "AWS-ApplyAnsiblePlaybooks" --document-version "\$LATEST" --targets '[{"Key":"tag:bloomstack","Values":["testing"]}]' --parameters '{"SourceType":["S3"],"SourceInfo":["{\"path\":\"https://bloomstack-ssm-test.s3.ap-south-1.amazonaws.com/update.yaml\"}\n"],"InstallDependencies":["False"],"PlaybookFile":["update.yaml"],"ExtraVariables":["SSM=True"],"Check":["False"],"Verbose":["-v"]}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --output-s3-bucket-name "bloomstack-ssm-test" --region ap-south-1
      - echo Build completed on `date`
