version: 0.2

env:
  variables:
    FRAPPE_USER: "frappe"
    BENCH_DIR: "/home/frappe/frappe-bench"

phases:
  install:
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws configure set aws_access_key_id $ACCESS_KEY
      - aws configure set aws_secret_access_key $SECRET_KEY
      - aws configure set region ap-south-1
      
  build:
    commands:
      - echo Build started on `date`
      - aws ssm send-command --document-name "AWS-RunAnsiblePlaybook" --document-version "1" --targets '[{"Key":"tag:bloomstack","Values":["true"]}]' --parameters '{"playbook":[""],"playbookurl":["https://raw.githubusercontent.com/DigiThinkIT/frappe/aws-test/update.yml"],"extravars":["SSM=True"],"check":["False"]}' --timeout-seconds 30 --max-concurrency "50" --max-errors "0" --region ap-south-1
