- hosts: localhost

  environment:
    NVM_DIR: /home/frappe/.nvm
    PATH: /home/frappe/.nvm/versions/node/v8.17.0/bin:{{ ansible_env.PATH }}

  tasks:
    - name: Update Staging Sites
      command: flock /tmp/bench.lock -c "bench update"
      args:
        chdir: /home/frappe/frappe-staging
    - name: Update Demo Sites
      command: flock /tmp/bench.lock -c "bench update"
      args:
        chdir: /home/frappe/frappe-production
